### ISSUE TITLE
genLabel "Mouse Neocortex +Adcy2 +CR +Calb2 +Grin3a +Inhbb +Nppc +Pde2a +RGS6 +RGS7 +SST +Sst +Zip1 +Znt3 GABARLower GLURHigher neuron (Huang2017)"

### ISSUE THREAD

**Issue by memartone** [tgbugs/pyontutils#42]
This neuron lists both CR and Calb2 but I can find neither in table 7s for the MNC.

**Comment by tgbugs** [comment]
This is caused by my [cre line equivalents](https://github.com/tgbugs/pyontutils/blob/52ce14cef6fd1f694c23d2ef2d27420620765ce9/neurondm/neurondm/models/huang2017.py#L54) which are not present in table 7, but are partially derived from [Figure 1E](https://www.ncbi.nlm.nih.gov/core/lw/2.0/html/tileshop_pmc/tileshop_pmc_inline.html?title=Click%20on%20image%20to%20zoom&p=PMC3&id=5772785_nihms927502f1.jpg). This may be a bit of an over interpretation on my part.
