### ISSUE TITLE
Martinotti cell-problems classifying

### ISSUE THREAD

**Issue by memartone** [tgbugs/pyontutils#48]
In all other neurons, you use "hasSomaLocatedIn", but in this class, you have "hasLocationPhenotype" and "LayerLocationPhenotype".  Please make it consistent.  I cannot return the Martinotti CUT neuron, however, even with this query: Neuron and (hasLocationPhenotype some neocortex) and ((hasExpressionPhenotype some PR_000015665) or (hasExpressionPhenotype some Sst) or (hasExpressionPhenotype some somatostatin) or (hasExpressionPhenotype some Sst-IRES-Cre))

**Comment by tgbugs** [comment]
The reason we have duplication in these cases is because those axioms are sourced from two nearly similar sources derived from neurolex and I have kept them both around until I can resolve which one is correct. This is one of the cases where the 'nearly' comes into account. Once I get those cases resolved it will show up as `hasSomaLocatedIn` and `hasLayerLocationPhenotype`. `hasLocationPhenotype` is the [super property](http://ontology.neuinfo.org/trees/query/rdfs:subPropertyOf/ilxtr:hasLocationPhenotype) in of both of those classes so I'm using it in the interim so the reasoning is consistent.

**Comment by memartone** [comment]
But the reasoning doesn’t seem to work, as if I use ‘hasLocationPhenotype”, it still doesn’t return the Martinotti cell.

**Comment by tgbugs** [comment]
This is due to a combination of two factors, the use of a deprecated identifier for somatostatin `NIFEXT:5116` and use of `hasLocationPhenotype` instead of hasSomaLocated in which the Neocortex +SOM neuron expects.

**Comment by tgbugs** [comment]
Now resolved since we switched to use phenotype indicators.
